// <auto-generated />
using System;
using ExampleEcom.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExampleEcom.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExampleEcom.Domain.Aggregates.ProductAggregates.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("number");

                    b.Property<bool>("SpacedSymbol")
                        .HasColumnType("boolean")
                        .HasColumnName("spaced_symbol");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("symbol");

                    b.Property<int>("SymbolOrientation")
                        .HasColumnType("integer")
                        .HasColumnName("symbol_orientation");

                    b.HasKey("Id");

                    b.ToTable("currency");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "???",
                            Name = "Abkhazian apsar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "?",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 6,
                            Code = "???",
                            Name = "Alderney pound",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "£",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 15,
                            Code = "???",
                            Name = "Artsakh dram",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "դր.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 177,
                            Code = "???",
                            Name = "Niue dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 204,
                            Code = "???",
                            Name = "Sahrawi peseta",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Ptas",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 252,
                            Code = "AED",
                            Name = "United Arab Emirates dirham",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "د.إ",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 3,
                            Code = "AFN",
                            Name = "Afghan afghani",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "؋",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 5,
                            Code = "ALL",
                            Name = "Albanian lek",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "L",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 14,
                            Code = "AMD",
                            Name = "Armenian dram",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "֏",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 65,
                            Code = "ANG",
                            Name = "Netherlands Antillean guilder",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "ƒ",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 10,
                            Code = "AOA",
                            Name = "Angolan kwanza",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Kz",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 13,
                            Code = "ARS",
                            Name = "Argentine peso",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 19,
                            Code = "AUD",
                            Name = "Australian dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 17,
                            Code = "AWG",
                            Name = "Aruban florin",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "ƒ",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 21,
                            Code = "AZN",
                            Name = "Azerbaijani manat",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₼",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 35,
                            Code = "BAM",
                            Name = "Bosnia and Herzegovina convertible mark",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "KM",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 25,
                            Code = "BBD",
                            Name = "Barbadian dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 24,
                            Code = "BDT",
                            Name = "Bangladeshi taka",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "৳",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 42,
                            Code = "BGN",
                            Name = "Bulgarian lev",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "лв.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 23,
                            Code = "BHD",
                            Name = "Bahraini dinar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = ".د.ب",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 44,
                            Code = "BIF",
                            Name = "Burundian franc",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Fr",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 30,
                            Code = "BMD",
                            Name = "Bermudian dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 40,
                            Code = "BND",
                            Name = "Brunei dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 33,
                            Code = "BOB",
                            Name = "Bolivian boliviano",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Bs.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 37,
                            Code = "BRL",
                            Name = "Brazilian real",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "R$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 22,
                            Code = "BSD",
                            Name = "Bahamian dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 51,
                            Code = "BTC",
                            Name = "Bitcoin",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₿",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 31,
                            Code = "BTN",
                            Name = "Bhutanese ngultrum",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Nu.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 36,
                            Code = "BWP",
                            Name = "Botswana pula",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "P",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 26,
                            Code = "BYN",
                            Name = "Belarusian ruble",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Br",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 28,
                            Code = "BZD",
                            Name = "Belize dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 47,
                            Code = "CAD",
                            Name = "Canadian dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 57,
                            Code = "CDF",
                            Name = "Congolese franc",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Fr",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 142,
                            Code = "CHF",
                            Name = "Swiss franc",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Fr.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 59,
                            Code = "CKD",
                            Name = "Cook Islands dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 53,
                            Code = "CLP",
                            Name = "Chilean peso",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 54,
                            Code = "CNY",
                            Name = "Renminbi/Chinese yuan",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "¥",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 55,
                            Code = "COP",
                            Name = "Colombian peso",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 61,
                            Code = "CRC",
                            Name = "Costa Rican colón",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₡",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 64,
                            Code = "CUP",
                            Name = "Cuban peso",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 48,
                            Code = "CVE",
                            Name = "Cape Verdean escudo",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 67,
                            Code = "CZK",
                            Name = "Czech koruna",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Kč",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 69,
                            Code = "DJF",
                            Name = "Djiboutian franc",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Fr",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 68,
                            Code = "DKK",
                            Name = "Danish krone",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "kr",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 71,
                            Code = "DOP",
                            Name = "Dominican peso",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "RD$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 8,
                            Code = "DZD",
                            Name = "Algerian dinar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "د.ج",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 76,
                            Code = "EGP",
                            Name = "Egyptian pound",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "£E",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 80,
                            Code = "ERN",
                            Name = "Eritrean nakfa",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Nfk.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 84,
                            Code = "ETB",
                            Name = "Ethiopian birr",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Br",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 4,
                            Code = "EUR",
                            Name = "Euro",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "€",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 88,
                            Code = "FJD",
                            Name = "Fijian dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 85,
                            Code = "FKP",
                            Name = "Falkland Islands pound",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "£",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 87,
                            Code = "FOK",
                            Name = "Faroese króna",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "kr",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 103,
                            Code = "GBP",
                            Name = "Sterling",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "£",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 94,
                            Code = "GEL",
                            Name = "Georgian lari",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₾",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 7,
                            Code = "GGP",
                            Name = "Guernsey pound",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "£",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 96,
                            Code = "GHS",
                            Name = "Ghanaian cedi",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₵",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 97,
                            Code = "GIP",
                            Name = "Gibraltar pound",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "£",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 93,
                            Code = "GMD",
                            Name = "Gambian dalasi",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "D",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 104,
                            Code = "GNF",
                            Name = "Guinean franc",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Fr",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 101,
                            Code = "GTQ",
                            Name = "Guatemalan quetzal",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Q",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 106,
                            Code = "GYD",
                            Name = "Guyanese dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 109,
                            Code = "HKD",
                            Name = "Hong Kong dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 108,
                            Code = "HNL",
                            Name = "Honduran lempira",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "L",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 63,
                            Code = "HRK",
                            Name = "Croatian kuna",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "kn",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 107,
                            Code = "HTG",
                            Name = "Haitian gourde",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "G",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 110,
                            Code = "HUF",
                            Name = "Hungarian forint",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Ft",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 113,
                            Code = "IDR",
                            Name = "Indonesian rupiah",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Rp",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 119,
                            Code = "ILS",
                            Name = "Israeli new shekel",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₪",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 117,
                            Code = "IMP",
                            Name = "Manx pound",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "£",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 32,
                            Code = "INR",
                            Name = "Indian rupee",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₹",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 115,
                            Code = "IQD",
                            Name = "Iraqi dinar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "ع.د",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 114,
                            Code = "IRR",
                            Name = "Iranian rial",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "﷼",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 111,
                            Code = "ISK",
                            Name = "Icelandic króna",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "kr",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 123,
                            Code = "JEP",
                            Name = "Jersey pound",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "£",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 121,
                            Code = "JMD",
                            Name = "Jamaican dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 125,
                            Code = "JOD",
                            Name = "Jordanian dinar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "د.ا",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 122,
                            Code = "JPY",
                            Name = "Japanese yen",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "¥",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 127,
                            Code = "KES",
                            Name = "Kenyan shilling",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Sh",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 134,
                            Code = "KGS",
                            Name = "Kyrgyz som",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "с",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 45,
                            Code = "KHR",
                            Name = "Cambodian riel",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "៛",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 128,
                            Code = "KID",
                            Name = "Kiribati dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 56,
                            Code = "KMF",
                            Name = "Comorian franc",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Fr",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 130,
                            Code = "KPW",
                            Name = "North Korean won",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₩",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 131,
                            Code = "KRW",
                            Name = "South Korean won",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₩",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 133,
                            Code = "KWD",
                            Name = "Kuwaiti dinar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "د.ك",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 49,
                            Code = "KYD",
                            Name = "Cayman Islands dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 126,
                            Code = "KZT",
                            Name = "Kazakhstani tenge",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₸",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 135,
                            Code = "LAK",
                            Name = "Lao kip",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₭",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 137,
                            Code = "LBP",
                            Name = "Lebanese pound",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "ل.ل",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 230,
                            Code = "LKR",
                            Name = "Sri Lankan rupee",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Rs",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 140,
                            Code = "LRD",
                            Name = "Liberian dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 138,
                            Code = "LSL",
                            Name = "Lesotho loti",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "L",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 141,
                            Code = "LYD",
                            Name = "Libyan dinar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "ل.د",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 163,
                            Code = "MAD",
                            Name = "Moroccan dirham",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "د.م.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 158,
                            Code = "MDL",
                            Name = "Moldovan leu",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "L",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 147,
                            Code = "MGA",
                            Name = "Malagasy ariary",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Ar",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 178,
                            Code = "MKD",
                            Name = "Macedonian denar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "ден",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 165,
                            Code = "MMK",
                            Name = "Burmese kyat",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Ks",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 160,
                            Code = "MNT",
                            Name = "Mongolian tögrög",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₮",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 145,
                            Code = "MOP",
                            Name = "Macanese pataca",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "MOP$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 154,
                            Code = "MRU",
                            Name = "Mauritanian ouguiya",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "UM",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 155,
                            Code = "MUR",
                            Name = "Mauritian rupee",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₨",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 150,
                            Code = "MVR",
                            Name = "Maldivian rufiyaa",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = ".ރ",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 148,
                            Code = "MWK",
                            Name = "Malawian kwacha",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "MK",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 156,
                            Code = "MXN",
                            Name = "Mexican peso",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 149,
                            Code = "MYR",
                            Name = "Malaysian ringgit",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "RM",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 164,
                            Code = "MZN",
                            Name = "Mozambican metical",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "MT",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 166,
                            Code = "NAD",
                            Name = "Namibian dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 175,
                            Code = "NGN",
                            Name = "Nigerian naira",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₦",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 173,
                            Code = "NIO",
                            Name = "Nicaraguan córdoba",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "C$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 180,
                            Code = "NOK",
                            Name = "Norwegian krone",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "kr",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 169,
                            Code = "NPR",
                            Name = "Nepalese rupee",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "रू",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 60,
                            Code = "NZD",
                            Name = "New Zealand dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 181,
                            Code = "OMR",
                            Name = "Omani rial",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "ر.ع.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 186,
                            Code = "PAB",
                            Name = "Panamanian balboa",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "B/.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 190,
                            Code = "PEN",
                            Name = "Peruvian sol",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "S/.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 188,
                            Code = "PGK",
                            Name = "Papua New Guinean kina",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "K",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 191,
                            Code = "PHP",
                            Name = "Philippine peso",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₱",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 182,
                            Code = "PKR",
                            Name = "Pakistani rupee",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₨",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 194,
                            Code = "PLN",
                            Name = "Polish złoty",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "zł",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 193,
                            Code = "PND",
                            Name = "Pitcairn Islands dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 242,
                            Code = "PRB",
                            Name = "Transnistrian ruble",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "р.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 189,
                            Code = "PYG",
                            Name = "Paraguayan guaraní",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₲",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 196,
                            Code = "QAR",
                            Name = "Qatari riyal",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "ر.ق",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 197,
                            Code = "RON",
                            Name = "Romanian leu",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "lei",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 214,
                            Code = "RSD",
                            Name = "Serbian dinar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "din.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 2,
                            Code = "RUB",
                            Name = "Russian ruble",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₽",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 199,
                            Code = "RWF",
                            Name = "Rwandan franc",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Fr",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 212,
                            Code = "SAR",
                            Name = "Saudi riyal",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "﷼",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 223,
                            Code = "SBD",
                            Name = "Solomon Islands dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 215,
                            Code = "SCR",
                            Name = "Seychellois rupee",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₨",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 231,
                            Code = "SDG",
                            Name = "Sudanese pound",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "ج.س.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 233,
                            Code = "SEK",
                            Name = "Swedish krona",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "kr",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 41,
                            Code = "SGD",
                            Name = "Singapore dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 18,
                            Code = "SHP",
                            Name = "Saint Helena pound",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "£",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 216,
                            Code = "SLL",
                            Name = "Sierra Leonean leone",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Le",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 225,
                            Code = "SLS",
                            Name = "Somaliland shilling",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Sl",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 224,
                            Code = "SOS",
                            Name = "Somali shilling",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Sh",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 232,
                            Code = "SRD",
                            Name = "Surinamese dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 229,
                            Code = "SSP",
                            Name = "South Sudanese pound",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "£",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 211,
                            Code = "STN",
                            Name = "São Tomé and Príncipe dobra",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Db",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 235,
                            Code = "SYP",
                            Name = "Syrian pound",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "£S",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 82,
                            Code = "SZL",
                            Name = "Swazi lilangeni",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "L",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 239,
                            Code = "THB",
                            Name = "Thai baht",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "฿",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 237,
                            Code = "TJS",
                            Name = "Tajikistani somoni",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "с.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 246,
                            Code = "TMT",
                            Name = "Turkmenistan manat",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "m.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 244,
                            Code = "TND",
                            Name = "Tunisian dinar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "د.ت",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 241,
                            Code = "TOP",
                            Name = "Tongan paʻanga",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "T$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 179,
                            Code = "TRY",
                            Name = "Turkish lira",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₺",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 243,
                            Code = "TTD",
                            Name = "Trinidad and Tobago dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 248,
                            Code = "TVD",
                            Name = "Tuvaluan dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 236,
                            Code = "TWD",
                            Name = "New Taiwan dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 238,
                            Code = "TZS",
                            Name = "Tanzanian shilling",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Sh",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 251,
                            Code = "UAH",
                            Name = "Ukrainian hryvnia",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₴",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 250,
                            Code = "UGX",
                            Name = "Ugandan shilling",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "USh",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 34,
                            Code = "USD",
                            Name = "United States dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 255,
                            Code = "UYU",
                            Name = "Uruguayan peso",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 256,
                            Code = "UZS",
                            Name = "Uzbekistani so'm",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Sʻ",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 260,
                            Code = "VED",
                            Name = "Venezuelan bolívar digital",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Bs.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 259,
                            Code = "VES",
                            Name = "Venezuelan sovereign bolívar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Bs.",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 261,
                            Code = "VND",
                            Name = "Vietnamese đồng",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₫",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 257,
                            Code = "VUV",
                            Name = "Vanuatu vatu",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Vt",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 209,
                            Code = "WST",
                            Name = "Samoan tālā",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "T",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 46,
                            Code = "XAF",
                            Name = "Central African CFA franc",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Fr",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 11,
                            Code = "XCD",
                            Name = "Eastern Caribbean dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "$",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 29,
                            Code = "XOF",
                            Name = "West African CFA franc",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "Fr",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 91,
                            Code = "XPF",
                            Name = "CFP franc",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "₣",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 263,
                            Code = "YER",
                            Name = "Yemeni rial",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "﷼",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 83,
                            Code = "ZAR",
                            Name = "South African rand",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "R",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 264,
                            Code = "ZMW",
                            Name = "Zambian kwacha",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "ZK",
                            SymbolOrientation = 0
                        },
                        new
                        {
                            Id = 265,
                            Code = "ZWB",
                            Name = "RTGS dollar",
                            Number = "0",
                            SpacedSymbol = false,
                            Symbol = "RTGS$",
                            SymbolOrientation = 0
                        });
                });

            modelBuilder.Entity("ExampleEcom.Domain.Aggregates.ProductAggregates.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("product");
                });

            modelBuilder.Entity("ExampleEcom.Domain.Aggregates.ProductAggregates.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_category_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("product_category");
                });

            modelBuilder.Entity("ExampleEcom.Domain.Aggregates.ProductAggregates.ProductPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_price");
                });

            modelBuilder.Entity("ExampleEcom.Domain.Aggregates.UserAggregates.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.HasIndex("UserId");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "e994d361-ec97-4409-8bdb-69ad4d4ca01d",
                            Name = "SystemAdmin",
                            NormalizedName = "SYSTEMADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "6eaeab58-0fd0-4849-893d-0d12f2bd8ce3",
                            Name = "SiteAdmin",
                            NormalizedName = "SITEADMIN"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "9a391831-de69-49c5-a02b-2ea5e34d4131",
                            Name = "SiteUser",
                            NormalizedName = "SITEUSER"
                        });
                });

            modelBuilder.Entity("ExampleEcom.Domain.Aggregates.UserAggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "52100990-dd09-43be-a6d1-8bf2343d2383",
                            Email = "system.admin@example-ecom.com",
                            EmailConfirmed = true,
                            FirstName = "SYSTEM",
                            LastName = "ADMIN",
                            LockoutEnabled = false,
                            NormalizedEmail = "SYSTEM.ADMIN@EXAMPLE-ECOM.COM",
                            NormalizedUserName = "SYSTEM_ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAECp/si0EGzIT/ph6LUE9osq8AVaGCjfHH1WsVCNCV6pCtM9AO3gE5jz2LJATWnuXrA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fe8f130d-872c-4a76-9955-cbc74fd66847",
                            TwoFactorEnabled = false,
                            UserName = "SYSTEM_ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("identity_role_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("identity_user_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("identity_user_login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("identity_user_role", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("identity_user_token", (string)null);
                });

            modelBuilder.Entity("ExampleEcom.Domain.Aggregates.ProductAggregates.Product", b =>
                {
                    b.HasOne("ExampleEcom.Domain.Aggregates.ProductAggregates.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ExampleEcom.Domain.Aggregates.ProductAggregates.ProductCategory", b =>
                {
                    b.HasOne("ExampleEcom.Domain.Aggregates.ProductAggregates.ProductCategory", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ExampleEcom.Domain.Aggregates.ProductAggregates.ProductPrice", b =>
                {
                    b.HasOne("ExampleEcom.Domain.Aggregates.ProductAggregates.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExampleEcom.Domain.Aggregates.ProductAggregates.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ExampleEcom.Domain.Aggregates.UserAggregates.Role", b =>
                {
                    b.HasOne("ExampleEcom.Domain.Aggregates.UserAggregates.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("ExampleEcom.Domain.Aggregates.UserAggregates.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ExampleEcom.Domain.Aggregates.UserAggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ExampleEcom.Domain.Aggregates.UserAggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("ExampleEcom.Domain.Aggregates.UserAggregates.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExampleEcom.Domain.Aggregates.UserAggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ExampleEcom.Domain.Aggregates.UserAggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExampleEcom.Domain.Aggregates.ProductAggregates.Product", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("ExampleEcom.Domain.Aggregates.ProductAggregates.ProductCategory", b =>
                {
                    b.Navigation("ChildCategories");
                });

            modelBuilder.Entity("ExampleEcom.Domain.Aggregates.UserAggregates.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
